### ISSUE TITLE
ustalenie terminu Daily (Dorota)

### ISSUE THREAD

**Issue by aerlevsedi** [m-przybylska/Integratec#7]

**Comment by itera-DG** [comment]
wyniki ankiety dot. dyspozycyjności: https://nuudel.digitalcourage.de/ehB3xu6m5w67tX6u

**Comment by itera-DG** [comment]
Uzgadniamy 2 Dailys tygodniowo po 30 minut w poniedziałki i środy. Dłuższe Weekly obywamy nadal w piątki.

Cel Daily: synchronizacja działań zespołu, kontrolować progress w kierunku celów wyznaczonych dla danego sprintu, stworzyć plan na kolejne 24-48 godzin

Pytania pomocnicze dla deweloperów:

1. Co zrobiłem/am od wczoraj/poprzedniego spotkania, aby wesprzeć zepół w osiągnięciu celu aktualnego Sprintu?
2. Co zrobię dziś/w kolejnym korku, aby wesprzeć zepół w osiągnięciu celu aktualnego Sprintu?
3. Czy istnieją jakieś przeszkody? Czy coś sprawia, że nie jestem w stanie wykonać kolejnych kroków na przód? 

**NO SIDE CONVERSATIONS** - kwestie do wyjaśnienia poszczególne osoby wyjaśniają np. tuż po daily

**RESULTS**
* improved communication
* identified impediments
* quick decision making

zasada: "Tylko zespół ma prawo głosu"
